Repository eclipse-hono/hono, pull requests merged in 2018-11, with the labels that each got.

#874 Fix String.format() errors
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
Labels: AMQP Adapter, enhancement

#844 [WIP] [#777] Add a build profile for Jaeger
  adapters/pom.xml
  bom/pom.xml
  deploy/src/main/deploy/openshift_s2i/jaeger/imagestream.yml
  site/content/deployment/openshift_s2i.md
Labels: Tracing

#884 [#777] Document usage of 'jaeger' maven profile
  site/content/admin-guide/monitoring-tracing-config.md
Labels: Tracing, documentation, enhancement

#875 Add hooks invoked during Command connection re-establishment.
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
Labels: C&C, enhancement

#889 Drop the vert.x metrics options, and allow disabling vertx metrics.
  core/src/main/java/org/eclipse/hono/config/VertxProperties.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
Labels: Metrics

#870 Deprecate Kura protocol adapter
  site/content/release-notes.md
Labels: documentation

#885 Upgrade to EnMasse 0.24.0
  deploy/src/main/deploy/openshift_s2i/addresses.json
  deploy/src/main/deploy/openshift_s2i/hono-address-space.yml
  deploy/src/main/deploy/openshift_s2i/hono-template.yml
  deploy/src/main/deploy/openshift_s2i/hono-tenant-template.yml
  deploy/src/main/deploy/openshift_s2i/resources/consumer-user-DEFAULT_TENTANT.json
  deploy/src/main/deploy/openshift_s2i/resources/downstream-user-http.json
  deploy/src/main/deploy/openshift_s2i/resources/downstream-user-mqtt.json
  site/content/deployment/openshift_s2i.md
Labels: enhancement

#877 [#876] Deleted devices should not be able to connect to the Mqtt adapter
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
Labels: MQTT Adapter, bug

#900 Fix issues and improve MQTT Adapter integration tests.
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
Labels: MQTT Adapter, enhancement

#907 [#895] Don't create error span if no client certs were given
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
Labels: HTTP Adapter, Tracing

#908 [#669] Handle one-way commands in the HTTP adapter.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  site/content/concepts/command-and-control.md
  site/content/concepts/command_control_concept_http.png
  site/content/concepts/command_control_concept_one_way_http.png
  site/content/getting-started.md
  site/diagrams/sequenceDiagrams/command_control_concept_http.txt
  site/diagrams/sequenceDiagrams/command_control_concept_one_way_http.txt
Labels: C&C, HTTP Adapter

#906 Fixed java command in sandbox documentation
  site/content/sandbox.md
Labels: documentation, enhancement

#898 [#888] Added interface CreditBasedSender with methods to check credits and to set a drain handler
  client/src/main/java/org/eclipse/hono/client/CreditBasedSender.java
  client/src/main/java/org/eclipse/hono/client/MessageSender.java
  client/src/main/java/org/eclipse/hono/client/RequestResponseClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
  client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
  client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
  client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
  site/content/release-notes.md
Labels: C&C, Client, enhancement

#918 Update instructions for running the Hono Integration Tests
  tests/readme.md
Labels: documentation, enhancement

#917 [#914] Add Tracer instance in EventBusService
  service-base/src/main/java/org/eclipse/hono/service/EventBusService.java
Labels: Tracing, enhancement

#925 Jenkins pipelines: Refactored with common methods to get jdk and maven versions.
  jenkins/Hono-Deploy-Eclipse-Pipeline.groovy
  jenkins/Hono-Deploy-Maven-Central-Pipeline.groovy
  jenkins/Hono-Nightly-Pipeline.groovy
  jenkins/Hono-PipelineUtils.groovy
  jenkins/Hono-Release-Pipeline.groovy
Labels: enhancement
