Repository eclipse-hono/hono, pull requests merged in 2018-10, with the labels that each got.

#815 [#784] Command & Control Concepts over AMQP Adapter
  site/content/concepts/command-and-control.md
  site/content/concepts/command_control_concept_amqp.png
Labels: AMQP Adapter, documentation

#834 Use OpenJDK 11 instead of OracleJDK 10 on Travis.
  .travis.yml
Labels: enhancement

#822 [#557] Pipeline script for Hono-CI jenkins build job
  jenkins/Hono-CI-Pipeline.groovy
  jenkins/Hono-PipelineUtils.groovy
Labels: enhancement

#833 [#825] Run password hash validation on vert.x worker thread.
  service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
  service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java
Labels: bug

#839 [ #557] Added pipeline for Hono-Website build job
  jenkins/Hono-Website-Pipeline.groovy
Labels: enhancement

#843 Checkout git repo without credentials for nightly build pipeline
  jenkins/Hono-Nightly-Pipeline.groovy
  jenkins/Hono-PipelineUtils.groovy
Labels: enhancement

#854 Add unit test for TriTuple
  core/src/test/java/org/eclipse/hono/util/TriTupleTest.java
Labels: enhancement

#861 [#557] Added pipelines to deploy artifacts to maven central and eclipse repos
  jenkins/Hono-Deploy-Eclipse-Pipeline.groovy
  jenkins/Hono-Deploy-Maven-Central-Pipeline.groovy
  jenkins/Hono-PipelineUtils.groovy
Labels: enhancement

#810 [#784] AMQP Adapter: Implement Command & Control
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
  service-base/src/main/java/org/eclipse/hono/service/command/Command.java
  service-base/src/main/java/org/eclipse/hono/service/command/CommandResponse.java
  tests/pom.xml
  tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterTestBase.java
Labels: AMQP Adapter, C&C

#863 Minor tracing improvement
  client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
  core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
Labels: Tracing, enhancement

#857 [#855] Provide Command and Control classes in hono-client.
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
  adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
  adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapAuthenticationHandler.java
  adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapPreSharedKeyHandler.java
  adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
  adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/ExtendedDevice.java
  adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/VertxBasedCoapAdapter.java
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
  adapters/kura/src/test/java/org/eclipse/hono/adapter/kura/KuraProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  adapters/mqtt-vertx/src/test/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapterTest.java
  client/src/main/java/org/eclipse/hono/client/AuthenticationServerClient.java
  client/src/main/java/org/eclipse/hono/client/Command.java
  client/src/main/java/org/eclipse/hono/client/CommandConnection.java
  client/src/main/java/org/eclipse/hono/client/CommandConsumer.java
  client/src/main/java/org/eclipse/hono/client/CommandContext.java
  client/src/main/java/org/eclipse/hono/client/CommandResponse.java
  client/src/main/java/org/eclipse/hono/client/CommandResponseSender.java
  client/src/main/java/org/eclipse/hono/client/CommandSubscription.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
  client/src/main/java/org/eclipse/hono/client/impl/CommandConnectionImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/CommandResponseSenderImpl.java
  client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
  client/src/test/java/org/eclipse/hono/client/CommandSubscriptionTest.java
  client/src/test/java/org/eclipse/hono/client/CommandTest.java
  client/src/test/java/org/eclipse/hono/client/impl/AbstractHonoClientTest.java
  client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
  client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
  client/src/test/java/org/eclipse/hono/client/impl/CommandConnectionImplTest.java
  core/src/main/java/org/eclipse/hono/auth/Device.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/main/java/org/eclipse/hono/service/auth/DeviceUser.java
  service-base/src/main/java/org/eclipse/hono/service/auth/delegating/DelegatingAuthenticationService.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoClientBasedAuthProvider.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
  service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
  service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducer.java
  service-base/src/main/java/org/eclipse/hono/service/monitoring/LoggingConnectionEventProducer.java
  service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
  site/content/release-notes.md
  tests/src/test/java/org/eclipse/hono/tests/auth/AuthServerAmqpIT.java
Labels: C&C, Client

#868 [#864, #865]: Improve configuration of the connection event producers
  adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
  service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducer.java
  service-base/src/main/java/org/eclipse/hono/service/monitoring/HonoEventConnectionEventProducer.java
  service-base/src/main/java/org/eclipse/hono/service/monitoring/LoggingConnectionEventProducer.java
  site/content/admin-guide/mqtt-adapter-config.md
  site/content/release-notes.md
Labels: EclipseInt, enhancement
