Repository eclipse-hono/hono, pull requests merged in 2018-07, with the labels that each got.

#678 [#319] Allow auto wiring of OpenTracing Tracer into HonoClientImpl.
  client/pom.xml
  client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
Labels: enhancement

#679 [#319] Include downstream messages in tracing.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
Labels: enhancement

#697 [#671] JMeter HonoSender: handling of TimeoutException
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
Labels: Load test

#700 [#699] JMeter plugin HonoReceiver: add check for request time calculation
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
Labels: Load test

#702 [#701] Improve JMeter plugin Receiver UI concerning useSenderTime options
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java
Labels: Load test

#704 [#703] JMeter plugin: Sender timeout configurable
  jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSenderSampler.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
Labels: Load test

#695 Improve error handling of HTTP adapter and HTTP based endpoints.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoAuthHandler.java
  service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
  service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
  service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
  service-base/src/test/java/org/eclipse/hono/service/auth/device/HonoAuthHandlerImplTest.java
Labels: HTTP Adapter, enhancement

#706 JMeter HonoSenderSamplerUI layout fix
  jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSamplerUI.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
Labels: Load test

#705 [#319] Support tracing of TenantClient requests.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  client/src/main/java/org/eclipse/hono/client/TenantClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
  client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/TenantClientImpl.java
  core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
Labels: enhancement

#714 amqp adapter - Improve device authentication
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/Config.java
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
Labels: AMQP Adapter

#715 [#708] Allow command responses reply-to without device id.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
  core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/main/java/org/eclipse/hono/service/command/Command.java
  service-base/src/main/java/org/eclipse/hono/service/command/CommandConnection.java
  service-base/src/main/java/org/eclipse/hono/service/command/CommandConnectionImpl.java
  service-base/src/main/java/org/eclipse/hono/service/command/CommandResponse.java
  service-base/src/main/java/org/eclipse/hono/service/command/CommandResponseSender.java
  service-base/src/main/java/org/eclipse/hono/service/command/CommandResponseSenderImpl.java
  service-base/src/test/java/org/eclipse/hono/service/command/CommandResponseTest.java
  service-base/src/test/java/org/eclipse/hono/service/command/CommandTest.java
  site/content/api/Command-And-Control-API.md
  site/content/api/command_control_Success.png
  site/content/release-notes.md
  site/diagrams/sequenceDiagrams/command_control_Success.txt
Labels: C&C

#721 JMeter plugin: Improve sender log output
  client/src/main/java/org/eclipse/hono/client/MessageConsumer.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractConsumer.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
Labels: Client, Load test, enhancement

#729 [#643] Telemetry based integration tests for the AMQP adapter.
  tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterBase.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryAmqpIT.java
Labels: AMQP Adapter

#648 [#645]: Document current metrics structure
  site/content/api/Metrics.md
Labels: Metrics, documentation

#710 [#319] Support tracing of RegistrationClient requests.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  client/src/main/java/org/eclipse/hono/client/RegistrationClient.java
  client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
Labels: Client, enhancement

#739 [#643] respond to Close frame emitted by clients
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
Labels: AMQP Adapter, bug

#737 [#331] Make connection timeout params configurable
  cli/src/main/java/org/eclipse/hono/cli/AbstractClient.java
  cli/src/main/java/org/eclipse/hono/cli/AppConfiguration.java
  cli/src/main/java/org/eclipse/hono/cli/Receiver.java
  cli/src/main/resources/application.yml
Labels: enhancement
