Repository eclipse-hono/hono, pull requests merged in 2019-03, with the labels that each got.

#1090 Fix Javadoc
  core/src/main/java/org/eclipse/hono/util/EventBusMessage.java
  service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
  service-base/src/main/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationService.java
Labels: documentation, enhancement

#1081 Language level 11 in code style.
  eclipse/hono-code-style.xml
Labels: enhancement

#1092 [#780] Extract dedicated client factory interfaces.
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
  client/src/main/java/org/eclipse/hono/client/ApplicationClientFactory.java
  client/src/main/java/org/eclipse/hono/client/ConnectionLifecycle.java
  client/src/main/java/org/eclipse/hono/client/CredentialsClientFactory.java
  client/src/main/java/org/eclipse/hono/client/DisconnectListener.java
  client/src/main/java/org/eclipse/hono/client/DownstreamSenderFactory.java
  client/src/main/java/org/eclipse/hono/client/HonoClient.java
  client/src/main/java/org/eclipse/hono/client/ReconnectListener.java
  client/src/main/java/org/eclipse/hono/client/RegistrationClientFactory.java
  client/src/main/java/org/eclipse/hono/client/TenantClientFactory.java
  client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
Labels: Client

#1082 [#1066] Add client certificate based authentication to CLI.
  cli/src/main/java/org/eclipse/hono/cli/AmqpSend.java
  site/content/user-guide/amqp-adapter.md
Labels: AMQP Adapter, documentation

#1028 Fix for #775 Support tenant-scoped command response link in HonoClient
  client/src/main/java/org/eclipse/hono/client/ApplicationClientFactory.java
  client/src/main/java/org/eclipse/hono/client/AsyncCommandClient.java
  client/src/main/java/org/eclipse/hono/client/HonoClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AsyncCommandClientImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/AsyncCommandResponseConsumerImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
Labels: C&C, Client

#1094 [#1024] Fix script based Kubernetes deployment
  deploy/src/main/deploy/kubernetes/kubernetes_deploy.sh
Labels: bug

#1098 [#1084] Remove obsolete java_client_sender guide and related classes
  example/src/main/java/org/eclipse/hono/vertx/example/HonoEventSender.java
  example/src/main/java/org/eclipse/hono/vertx/example/HonoExampleApplication.java
  example/src/main/java/org/eclipse/hono/vertx/example/HonoTelemetrySender.java
  example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
  example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleConstants.java
  example/src/main/java/org/eclipse/hono/vertx/example/base/HonoSenderBase.java
  site/content/dev-guide/java_client_sender.md
Labels: documentation

#1104 Remove duplicate entry in helm template
  deploy/src/main/deploy/helm/templates/artemis/artemis-secret.yaml
Labels: enhancement

#1096 TenantService: Add support for enforcing valid Base64 encoding
  service-base/src/main/java/org/eclipse/hono/service/tenant/CompleteBaseTenantService.java
  service-base/src/test/java/org/eclipse/hono/service/tenant/CompleteBaseTenantServiceTest.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/registry/TenantAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/registry/TenantHttpIT.java
Labels: Device Registry, enhancement

#1107 [#930][#1103] Fixes regarding handling of "last-via" property.
  service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
  service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
Labels: Device Registry

#1089 [#1083] Unified file paths in documentation, removed shell prompts.
  CONTRIBUTING.md
  demo-certs/README.md
  site/content/admin-guide/amqp-adapter-config.md
  site/content/admin-guide/amqp-network-config.md
  site/content/admin-guide/auth-server-config.md
  site/content/admin-guide/device-registry-config.md
  site/content/admin-guide/http-adapter-config.md
  site/content/admin-guide/kura-adapter-config.md
  site/content/admin-guide/monitoring-tracing-config.md
  site/content/admin-guide/mqtt-adapter-config.md
  site/content/admin-guide/secure_communication.md
  site/content/community/contributing.md
  site/content/deployment/docker-swarm.md
  site/content/deployment/kubernetes.md
  site/content/deployment/resource-limitation.md
  site/content/dev-guide/java_client_consumer.md
  site/content/download.md
  site/content/getting-started.md
  site/content/user-guide/amqp-adapter.md
  site/content/user-guide/device-registry.md
  site/content/user-guide/http-adapter.md
  site/content/user-guide/mqtt-adapter.md
  tests/readme.md
Labels: documentation

#1078 Add Http based LoRa Adapter with support for different providers
  adapters/lora-vertx/pom.xml
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/Application.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/Config.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraCommandProperties.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraConstants.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraMessageType.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ActilityProvider.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/EverynetProvider.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/KerlinkProvider.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProvider.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProviderDownlinkException.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProviderMalformedPayloadException.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraUtils.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ObjeniousProvider.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ProximusProvider.java
  adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ThingsNetworkProvider.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapterTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/LoraUtilsTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ActilityProviderTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/EverynetProviderTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/LoraTestUtil.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ObjeniousProviderTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ProximusProviderTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ThingsNetworkProviderTest.java
  adapters/lora-vertx/src/test/resources/logback-test.xml
  adapters/lora-vertx/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  adapters/lora-vertx/src/test/resources/payload/actility.uplink.json
  adapters/lora-vertx/src/test/resources/payload/everynet.uplink.json
  adapters/lora-vertx/src/test/resources/payload/kerlink.uplink.json
  adapters/lora-vertx/src/test/resources/payload/objenious.downlink.json
  adapters/lora-vertx/src/test/resources/payload/objenious.join.json
  adapters/lora-vertx/src/test/resources/payload/objenious.uplink.json
  adapters/lora-vertx/src/test/resources/payload/proximus.uplink.json
  adapters/lora-vertx/src/test/resources/payload/ttn.uplink.json
  adapters/pom.xml
  bom/pom.xml
  core/src/main/java/org/eclipse/hono/util/HexDecodingException.java
  core/src/main/java/org/eclipse/hono/util/Strings.java
  core/src/test/java/org/eclipse/hono/util/StringsTest.java
Labels: enhancement

#937 [#927] Limit number of connections per tenant
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  bom/pom.xml
  core/src/main/java/org/eclipse/hono/util/TenantConstants.java
  core/src/main/java/org/eclipse/hono/util/TenantObject.java
  core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
  service-base/pom.xml
  service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/main/java/org/eclipse/hono/service/plan/NoopResourceLimitChecks.java
  service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
  service-base/src/main/java/org/eclipse/hono/service/plan/ResourceLimitChecks.java
Labels: MQTT Adapter

#938 Add command and control example to AMQP adpater user guide.
  cli/src/main/java/org/eclipse/hono/cli/AmqpCliClient.java
  cli/src/main/java/org/eclipse/hono/cli/CommandAndControlClient.java
  cli/src/main/java/org/eclipse/hono/cli/TelemetryAndEventCli.java
  cli/src/main/resources/application.yml
  site/content/user-guide/amqp-adapter.md
Labels: AMQP Adapter, documentation

#1118 Fix typo in class name in 1.0M1 release notes
  site/content/release-notes.md
Labels: documentation

#1117 Added docs and scripts to deploy Hono on Azure Kubernetes Services
  deploy/src/main/deploy/kubernetes/azure_deploy.sh
  deploy/src/main/deploy/kubernetes/azure_undeploy.sh
  deploy/src/main/deploy/resource-descriptors/azure/dispatch-router-ext-svc.yaml
  deploy/src/main/deploy/resource-descriptors/azure/hono-adapter-amqp-vertx-ext-svc.yaml
  deploy/src/main/deploy/resource-descriptors/azure/hono-adapter-http-vertx-ext-svc.yaml
  deploy/src/main/deploy/resource-descriptors/azure/hono-adapter-kura-ext-svc.yaml
  deploy/src/main/deploy/resource-descriptors/azure/hono-adapter-mqtt-vertx-ext-svc.yaml
  deploy/src/main/deploy/resource-descriptors/azure/hono-service-device-registry-ext-svc.yaml
  push_hono_images_private.sh
  site/content/deployment/azure-aks.md
Labels: documentation, enhancement
