Repository eclipse-hono/hono, pull requests merged in 2019-02, with the labels that each got.

#1021 [#1020] Fix wrong exceptions being thrown
  client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
Labels: Client, bug

#1018 [#961] Include payload size in reporting of telemetry messages.
  adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  deploy/src/main/config/grafana/dashboard-definitions/message-details.json
  deploy/src/main/config/grafana/dashboard-definitions/overview.json
  service-base/src/main/java/org/eclipse/hono/service/metric/AbstractLegacyMetricsConfig.java
  service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
  service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
  service-base/src/main/java/org/eclipse/hono/service/metric/NoopBasedMetrics.java
  service-base/src/test/java/org/eclipse/hono/service/metric/MicrometerBasedMetricsTest.java
  site/content/api/Metrics.md
Labels: CoAP Adapter, HTTP Adapter, MQTT Adapter, Metrics

#1010 [#931] Check or set connection limit in MQTT adapter
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  core/src/main/java/org/eclipse/hono/config/ProtocolAdapterProperties.java
  site/content/admin-guide/mqtt-adapter-config.md
  site/content/release-notes.md
Labels: MQTT Adapter

#1029 Enforce Java 11 during the build
  pom.xml
Labels: enhancement

#1030 Use common method for checking if tenant is enabled for adapter
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
Labels: AMQP Adapter, HTTP Adapter, MQTT Adapter, enhancement

#1032 Fix JavaDoc.
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
Labels: documentation

#1036 Helm deployment documentation
  site/content/deployment/kubernetes.md
Labels: documentation

#1031 [#1015] Move EventBusAuthenticationService class to top level
  service-base/src/main/java/org/eclipse/hono/service/auth/EventBusAuthenticationService.java
  service-base/src/main/java/org/eclipse/hono/service/auth/HonoSaslAuthenticatorFactory.java
Labels: enhancement

#1034 Log the exception when parsing the trust anchor from the tenant.
  core/src/main/java/org/eclipse/hono/util/TenantObject.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java
Labels: enhancement

#965 [#958] Part 1: Get the tenant and device ids into command response
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  client/src/main/java/org/eclipse/hono/client/Command.java
  client/src/main/java/org/eclipse/hono/client/CommandResponse.java
  client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
  client/src/test/java/org/eclipse/hono/client/CommandTest.java
Labels: C&C

#1041 [#958] Part 2: Add device and tenant ids to command response amqp messages.
  client/src/main/java/org/eclipse/hono/client/impl/CommandResponseSenderImpl.java
Labels: C&C

#1042 Replace the fields of CommandResponse with a message for storing the properties.
  client/src/main/java/org/eclipse/hono/client/CommandResponse.java
  client/src/main/java/org/eclipse/hono/client/impl/CommandResponseSenderImpl.java
  client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
Labels: C&C, enhancement

#1044 [#961] Use "Timer" meter for command messages.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandHandler.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  client/src/main/java/org/eclipse/hono/client/Command.java
  deploy/src/main/config/grafana/dashboard-definitions/overview.json
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/main/java/org/eclipse/hono/service/metric/LegacyMetrics.java
  service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
  service-base/src/main/java/org/eclipse/hono/service/metric/MetricsTags.java
  service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedLegacyMetrics.java
  service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
  service-base/src/main/java/org/eclipse/hono/service/metric/NoopBasedMetrics.java
  service-base/src/main/java/org/eclipse/hono/service/metric/NoopLegacyMetrics.java
  service-base/src/test/java/org/eclipse/hono/service/metric/LegacyMetricsConfigTest.java
  site/content/api/Metrics.md
Labels: Metrics

#1045 [#1022] Include SASL handshake in ClientConfigProperties connectTimeout
  client/src/test/java/org/eclipse/hono/client/impl/HonoClientImplTest.java
  core/src/main/java/org/eclipse/hono/config/ClientConfigProperties.java
  core/src/main/java/org/eclipse/hono/connection/ConnectTimeoutException.java
  core/src/main/java/org/eclipse/hono/connection/impl/ConnectionFactoryImpl.java
  core/src/test/java/org/eclipse/hono/connection/impl/ConnectionFactoryImplTest.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/AbstractClient.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
  site/content/admin-guide/hono-client-configuration.md
  site/content/release-notes.md
Labels: Client, enhancement

#1050 Minor fixes and improvements
  adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
  deploy/src/main/deploy/example-device-identities.json
  example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
Labels: enhancement

#1051 Add missing @Override annotations
  adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/PreSharedKeyDeviceIdentity.java
  adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/VertxBasedCoapAdapter.java
  client/src/main/java/org/eclipse/hono/client/impl/CommandConnectionImpl.java
  service-base/src/main/java/org/eclipse/hono/service/metric/LegacyMetricsConfig.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
Labels: enhancement

#1053 Fix tracer param not being passed on
  service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java
Labels: bug

#1033 Fix in file `device-identities.json` in test resources
  services/device-registry/src/test/resources/device-identities.json
Labels: Sandbox

#1047 [#926] Support authorization of multiple gateways per device.
  service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
  service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
  site/content/admin-guide/device-registry-config.md
  site/content/release-notes.md
  tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
  tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
Labels: Device Registry, enhancement

#1054 [#1046][#1012] Fix encoding of OpenTracing span context in AMQP message
  client/src/main/java/org/eclipse/hono/client/CommandConsumer.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
  client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
  client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
  client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
  client/src/test/java/org/eclipse/hono/client/impl/TenantClientImplTest.java
  core/src/main/java/org/eclipse/hono/tracing/MessageAnnotationsExtractAdapter.java
  core/src/main/java/org/eclipse/hono/tracing/MessageAnnotationsInjectAdapter.java
  core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
  core/src/test/java/org/eclipse/hono/tracing/MessageAnnotationsInjectExtractAdapterTest.java
  service-base/src/main/java/org/eclipse/hono/service/amqp/RequestResponseEndpoint.java
Labels: Tracing, bug

#1052 Add 'MissingOverride' checkstyle module
  legal/src/main/resources/checkstyle/default.xml
Labels: enhancement

#1061 Replace Spring Boot Actuator with vertx-web based Prometheus endpoint.
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/Application.java
  adapters/pom.xml
  bom/pom.xml
  deploy/src/main/config/grafana/dashboard-definitions/overview.json
  deploy/src/main/deploy/docker/swarm_deploy.sh
  deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
  deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yml
  deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
  deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
  deploy/src/main/deploy/helm/templates/hono-service-auth/hono-service-auth-deployment.yaml
  deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-deployment.yaml
  deploy/src/main/deploy/resource-descriptors/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
  deploy/src/main/deploy/resource-descriptors/hono-adapter-http/hono-adapter-http-vertx-deployment.yml
  deploy/src/main/deploy/resource-descriptors/hono-adapter-kura/hono-adapter-kura-deployment.yaml
  deploy/src/main/deploy/resource-descriptors/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
  deploy/src/main/deploy/resource-descriptors/hono-service-auth/hono-service-auth-deployment.yaml
  deploy/src/main/deploy/resource-descriptors/hono-service-device-registry/hono-service-device-registry-deployment.yaml
  service-base/pom.xml
  service-base/src/main/java/org/eclipse/hono/service/VertxBasedHealthCheckServer.java
  service-base/src/main/java/org/eclipse/hono/service/metric/PrometheusScrapingResource.java
  services/auth/src/main/java/org/eclipse/hono/service/auth/impl/Application.java
  services/auth/src/main/java/org/eclipse/hono/service/auth/impl/ApplicationConfig.java
  services/pom.xml
  tests/pom.xml
  tests/src/test/resources/amqp/application.yml
  tests/src/test/resources/auth/application.yml
  tests/src/test/resources/deviceregistry/application.yml
  tests/src/test/resources/http/application.yml
  tests/src/test/resources/mqtt/application.yml
Labels: Metrics

#1068 Fix description of device registry in readme: add tenant API.
  services/device-registry/readme.md
Labels: documentation

#1063 Update S2I deployment to follow actuator removal
  deploy/src/main/deploy/openshift/hono-template.yml
  deploy/src/main/deploy/resource-descriptors/prometheus/instance.yml
Labels: Metrics

#1040 Proposal for #732
  core/src/test/java/org/eclipse/hono/config/AbstractConfigTest.java
  core/src/test/java/org/eclipse/hono/config/KeyLoaderTest.java
  demo-certs/README.md
  demo-certs/ca_opts
  demo-certs/certs/amqp-adapter-cert.pem
  demo-certs/certs/amqp-adapter-key.pem
  demo-certs/certs/amqpKeyStore.p12
  demo-certs/certs/artemis-cert.pem
  demo-certs/certs/artemis-key.pem
  demo-certs/certs/artemisKeyStore.p12
  demo-certs/certs/auth-server-cert.pem
  demo-certs/certs/auth-server-key.pem
  demo-certs/certs/authServerKeyStore.p12
  demo-certs/certs/ca-cert.pem
  demo-certs/certs/ca-key.pem
  demo-certs/certs/coap-adapter-cert.pem
  demo-certs/certs/coap-adapter-key.pem
  demo-certs/certs/coapKeyStore.p12
  demo-certs/certs/device-4711-cert.pem
  demo-certs/certs/device-4711-key.pem
  demo-certs/certs/device-certs.properties
  demo-certs/certs/device-registry-cert.pem
  demo-certs/certs/device-registry-key.pem
  demo-certs/certs/deviceRegistryKeyStore.p12
  demo-certs/certs/hono-messaging-cert.pem
  demo-certs/certs/hono-messaging-key.pem
  demo-certs/certs/honoKeyStore.p12
  demo-certs/certs/http-adapter-cert.pem
  demo-certs/certs/http-adapter-key.pem
  demo-certs/certs/httpKeyStore.p12
  demo-certs/certs/kura-adapter-cert.pem
  demo-certs/certs/kura-adapter-key.pem
  demo-certs/certs/kuraKeyStore.p12
  demo-certs/certs/mqtt-adapter-cert.pem
  demo-certs/certs/mqtt-adapter-key.pem
  demo-certs/certs/mqttKeyStore.p12
  demo-certs/certs/qdrouter-cert.pem
  demo-certs/certs/qdrouter-key.pem
  demo-certs/certs/root-cert.pem
  demo-certs/certs/root-key.pem
  demo-certs/certs/trust-anchor.properties
  demo-certs/certs/trustStore.jks
  demo-certs/certs/trusted-certs.pem
  demo-certs/create_certs.sh
  deploy/pom.xml
  deploy/src/main/deploy/example-credentials.json
  deploy/src/main/deploy/example-tenants.json
  service-base/src/test/java/org/eclipse/hono/service/AbstractServiceBaseTest.java
  service-base/src/test/java/org/eclipse/hono/service/registration/RegistrationAssertionHelperImplTest.java
  site/content/user-guide/http-adapter.md
  site/content/user-guide/mqtt-adapter.md
Labels: documentation
