Repository eclipse-hono/hono, pull requests merged in 2019-06, with the labels that each got.

#1277 Fix arguments.
  adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
Labels: SigFox Adapter

#1281 [#1245] Replace 'gw-supported with 'via' in assertRegistration response
  core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
  service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
  site/content/api/Device-Registration-API.md
  site/content/api/assertDeviceRegistration_Success.png
  site/content/release-notes.md
  site/diagrams/sequenceDiagrams/assertDeviceRegistration_Success.txt
Labels: Device Registry

#1280 Adjust heading levels to start with h2 per page.
  site/content/admin-guide/secure_communication.md
  site/content/api/Authentication-API.md
  site/content/api/Command-And-Control-API.md
  site/content/api/Credentials-API.md
  site/content/api/Device-Registration-API.md
  site/content/api/Event-API.md
  site/content/api/Telemetry-API.md
Labels: documentation, website

#1285 Drop travis.sh and prevent running mvn twice
  .travis.yml
  travis.sh
Labels: enhancement

#1274 [#1245] Add new Device Connection API documentation
  site/content/api/Device-Connection-API.md
  site/content/api/connectToDeviceConnection.png
  site/content/api/getLastKnownGatewayForDevice_Success.png
  site/content/api/setLastKnownGatewayForDevice_Success.png
  site/diagrams/sequenceDiagrams/connectToDeviceConnection_Success.txt
  site/diagrams/sequenceDiagrams/getLastKnownGatewayForDevice_Success.txt
  site/diagrams/sequenceDiagrams/setLastKnownGatewayForDevice_Success.txt
Labels: C&C

#1293 [#1109] Delete old files when building web site.
  jenkins/Hono-Website-Pipeline.groovy
Labels: website

#1294 [#1109] Disable section with users of Hono on landing page.
  site/homepage/config.toml
Labels: website

#1290 [#1245] Add new Device Connection API classes
  client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
  client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
  client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
  core/src/main/java/org/eclipse/hono/util/DeviceConnectionConstants.java
  core/src/main/java/org/eclipse/hono/util/DeviceConnectionResult.java
  service-base/src/main/java/org/eclipse/hono/service/deviceconnection/BaseDeviceConnectionService.java
  service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
  service-base/src/test/java/org/eclipse/hono/service/deviceconnection/BaseDeviceConnectionServiceTest.java
Labels: Device Registry

#1299 [#1109] Change Hono logo in documentation to match the one on homepage.
  site/documentation/layouts/partials/logo.html
  site/documentation/static/css/hono.css
  site/documentation/static/images/HONO-Logo_Bild-Wort_quer-w-310x120px.svg
  site/homepage/static/img/HONO-Logo_Bild-Wort_quer-s-118x46px.png
  site/homepage/static/img/HONO-Logo_Bild-Wort_quer-s-120x46px.png
Labels: website

#1300 [#1109] Fix links to API spec in release-notes.
  site/homepage/content/release-notes.md
Labels: website

#1295 Fix for #1288 flowLatency delays creation of senders unnecessarily long
  client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
  client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
Labels: Client, enhancement

#1292 Fix grafana dashboard for JVM details
  deploy/src/main/config/grafana/dashboard-definitions/jvm-details.json
Labels: Metrics, bug

#1298 [#1073] Change southbound control endpoint names
  adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
  adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterLegacyEndpointTest.java
  adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
  adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterLegacyEndpointTest.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
  adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterLegacyEndpointTest.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionLegacyEndpointTest.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/MqttContextTest.java
  adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
  client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
  core/src/main/java/org/eclipse/hono/util/CommandConstants.java
  core/src/test/java/org/eclipse/hono/util/ResourceIdentifierTest.java
  example/src/main/java/org/eclipse/hono/devices/HonoHttpDevice.java
  service-base/src/main/java/org/eclipse/hono/service/metric/MetricsTags.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlLegacyEndpointAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/EventLegacyCommandEndpointHttpIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/http/TelemetryLegacyCommandEndpointHttpIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlLegacyEndpointMqttIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
Labels: C&C

#1306 Handle errors occurring in receiver messageHandler
  client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
Labels: Client

#1305 [#1286] Handle error when creating client
  client/src/main/java/org/eclipse/hono/client/impl/CachingClientFactory.java
Labels: Client

#1310 Append the site title to the page title in pages on the homepage.
  site/homepage/layouts/partials/head.html
Labels: website

#1309 Add preview card to be used by twitter.
  site/documentation/config.toml
  site/documentation/layouts/partials/custom-header.html
  site/homepage/config.toml
Labels: website

#1308 Add description of the release process regarding the documentation.
  site/readme.md
Labels: documentation, website

#1304 Add missing "algorithm" field to the trust-ca object
  site/documentation/static/api/device-registry-v1.yaml
Labels: Device Registry

#1315 Fix Twitter preview card.
  site/documentation/config.toml
  site/documentation/layouts/partials/custom-header.html
  site/documentation/static/images/twitter_image.png
  site/homepage/config.toml
  site/homepage/layouts/partials/head.html
  site/homepage/static/img/twitter_image.png
Labels: website

#1311 Fix links to the documentation in Javadoc.
  adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-vertx/readme.md
  adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  adapters/mqtt-vertx/readme.md
  client/src/main/java/org/eclipse/hono/client/CommandClient.java
  client/src/main/java/org/eclipse/hono/client/CredentialsClient.java
  client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
  client/src/main/java/org/eclipse/hono/client/RegistrationClient.java
  client/src/main/java/org/eclipse/hono/client/TenantClient.java
  client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
  core/src/main/java/org/eclipse/hono/auth/EncodedPassword.java
  core/src/main/java/org/eclipse/hono/auth/HonoPasswordEncoder.java
  core/src/main/java/org/eclipse/hono/config/ProtocolAdapterProperties.java
  core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
  core/src/main/java/org/eclipse/hono/util/TenantObject.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoClientBasedAuthProvider.java
  service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java
  service-base/src/main/java/org/eclipse/hono/service/credentials/CompleteCredentialsService.java
  service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsAmqpEndpoint.java
  service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsHttpEndpoint.java
  service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsService.java
  service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
  service-base/src/main/java/org/eclipse/hono/service/registration/CompleteRegistrationService.java
  service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationAmqpEndpoint.java
  service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationHttpEndpoint.java
  service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationService.java
  service-base/src/main/java/org/eclipse/hono/service/tenant/CompleteTenantService.java
  service-base/src/main/java/org/eclipse/hono/service/tenant/TenantAmqpEndpoint.java
  service-base/src/main/java/org/eclipse/hono/service/tenant/TenantHttpEndpoint.java
  service-base/src/main/java/org/eclipse/hono/service/tenant/TenantService.java
  services/device-registry/readme.md
  services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/Application.java
Labels: documentation

#1321 [#1289] Disable auto-accept for command receiver links
  client/src/main/java/org/eclipse/hono/client/HonoConnection.java
  client/src/main/java/org/eclipse/hono/client/impl/DeviceSpecificCommandConsumer.java
  client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/TenantScopedCommandConsumer.java
  client/src/test/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImplTest.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
Labels: Client, bug

#1318 [#1317] Use Minikube in Getting Started guide.
  site/documentation/content/deployment/create-kubernetes-cluster.md
  site/documentation/content/deployment/docker-swarm.md
  site/documentation/content/deployment/helm-based-deployment.md
  site/documentation/content/dev-guide/building_hono.md
  site/documentation/content/dev-guide/java_client_consumer.md
  site/homepage/content/downloads.md
  site/homepage/content/getting-started.md
Labels: documentation, website

#1291 Migrate PrometheusBasedResourceLimitChecks tests to junit5
  service-base/src/test/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecksTest.java
Labels: enhancement

#1320 [#1245] Use Device Connection API for the gateway mapping feature
  adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
  adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
  adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  client/src/main/java/org/eclipse/hono/client/GatewayMapper.java
  client/src/main/java/org/eclipse/hono/client/impl/GatewayMapperImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/GatewayMappingCommandHandler.java
  client/src/test/java/org/eclipse/hono/client/impl/GatewayMapperImplTest.java
  client/src/test/java/org/eclipse/hono/client/impl/GatewayMappingCommandHandlerTest.java
  client/src/test/java/org/eclipse/hono/client/impl/HonoClientUnitTestHelper.java
  deploy/src/main/deploy/example-permissions.json
  deploy/src/main/sandbox/sandbox-permissions.json
  service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
  service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
  service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
  tests/src/test/resources/auth/permissions.json
Labels: C&C

#1314 Change credentials model and drop "delete" operation
  site/documentation/static/api/device-registry-v1.yaml
Labels: Device Registry

#1263 [#1262] Close mqtt connection when a telemetry/event message cannot be processed.
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
Labels: MQTT Adapter

#1323 [#1255] Let CommandClient instance be scoped to a tenant
  cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
  client/src/main/java/org/eclipse/hono/client/ApplicationClientFactory.java
  client/src/main/java/org/eclipse/hono/client/CommandClient.java
  client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
  client/src/main/java/org/eclipse/hono/client/impl/ApplicationClientFactoryImpl.java
  client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
  client/src/test/java/org/eclipse/hono/client/impl/CommandClientImplTest.java
  example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
  jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoCommander.java
  tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
Labels: C&C

#1325 [#1262] Update release notes.
  site/homepage/content/release-notes.md
Labels: documentation
