Repository eclipse-hono/hono, pull requests merged in 2021-08, with the labels that each got.

#2807 Fix error-handling when getting credentials
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsService.java
  services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsServiceTest.java
  services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsServiceTestBase.java
  services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
  services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
  services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/JdbcBasedCredentialsServiceTest.java
  services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
Labels: Device Registry

#2811 [#2725] Add fix for TOC indentation in documentation.
  site/documentation/static/css/hugo-theme.css
Labels: bug, website

#2804 [#2028] Change adapter instance id format
  clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
  core/src/main/java/org/eclipse/hono/util/KubernetesContainerUtil.java
  legal/src/main/resources/legal/NOTICE.md
Labels: C&C

#2813 Use SpanContext param in ConnectionEventProducer methods
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
  adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/AbstractMessageSenderConnectionEventProducer.java
  adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/ConnectionEventProducer.java
  adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/LoggingConnectionEventProducer.java
  adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
  adapter-base/src/test/java/org/eclipse/hono/adapter/monitoring/HonoEventConnectionEventProducerTest.java
  adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/amqp-vertx-base/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
  adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
Labels: Tracing

#2817 Make regex for validating hashed-password auth-ids configurable
  core/src/main/java/org/eclipse/hono/config/AuthenticatingClientConfigProperties.java
  core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java
  core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordCredential.java
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
  services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
  services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/config/DeviceServiceProperties.java
  services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/config/TenantServiceProperties.java
  services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/MongoDbBasedRegistrationConfigProperties.java
  site/documentation/content/admin-guide/jdbc-device-registry-config.md
  site/documentation/content/admin-guide/mongodb-device-registry-config.md
  site/homepage/content/release-notes.md
Labels: Feature Request, MongoDB Device Registry, JDBC Device Registry

#2801 [#2780] Wait for record future completion before commit
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
  clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumerTest.java
  test-utils/kafka-test-utils/src/main/java/org/eclipse/hono/kafka/test/KafkaMockConsumer.java
Labels: C&C

#2808 Remove Quarkus specific Infinispan client project
  bom/pom.xml
  client-device-connection-infinispan-quarkus/pom.xml
  client-device-connection-infinispan-quarkus/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/quarkus/CommonCacheConfig.java
  client-device-connection-infinispan-quarkus/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/quarkus/InfinispanRemoteConfigurationProperties.java
  client-device-connection-infinispan-quarkus/src/test/resources/application.yaml
  client-device-connection-infinispan/pom.xml
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CommonCacheConfig.java
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CommonCacheOptions.java
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/InfinispanRemoteConfigurationOptions.java
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/InfinispanRemoteConfigurationProperties.java
  client-device-connection-infinispan/src/main/resources/META-INF/native-image/org.eclipse.hono/client-device-connection-infinispan/native-image.properties
  client-device-connection-infinispan/src/main/resources/META-INF/native-image/org.eclipse.hono/client-device-connection-infinispan/reflection-config.json
  client-device-connection-infinispan/src/main/resources/META-INF/native-image/org.eclipse.hono/client-device-connection-infinispan/resources-config.json
  client-device-connection-infinispan/src/main/resources/application.properties
  client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/QuarkusPropertyBindingTest.java
  client-device-connection-infinispan/src/test/resources/application.yaml
  pom.xml
  services/command-router-quarkus/pom.xml
  services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/DeviceConnectionInfoProducer.java
Labels: enhancement

#2810 Replace Quarkus specific property binding mechanism
  adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/monitoring/quarkus/ConnectionEventProducerConfig.java
  adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
  adapter-base/pom.xml
  adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/ConnectionEventProducerConfig.java
  adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/ConnectionEventProducerOptions.java
  adapter-base/src/test/java/org/eclipse/hono/adapter/quarkus/QuarkusPropertyBindingTest.java
  adapter-base/src/test/resources/application.yaml
Labels: enhancement

#2821 Prevent tenants from having empty CA array
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
  services/device-registry-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
  site/homepage/content/release-notes.md
  tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
Labels: bug, MongoDB Device Registry

#2824 Fix Kafka configuration on Sandbox
  deploy/src/main/sandbox/hono-values.yml
Labels: Sandbox, Deployment

#2822 [#2028] Add AdapterInstanceStatusService in Command Router
  bom/pom.xml
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/AdapterInstanceStatusProvider.java
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
  client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
  clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
  core/src/main/java/org/eclipse/hono/util/AdapterInstanceStatus.java
  core/src/main/java/org/eclipse/hono/util/CommandConstants.java
  legal/src/main/resources/legal/DEPENDENCIES
  legal/src/main/resources/legal/hono-maven.deps
  services/command-router-base/pom.xml
  services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/AdapterInstanceStatusService.java
  services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/CommandRouterServiceConfigProperties.java
  services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
  services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/KubernetesBasedAdapterInstanceStatusService.java
  services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImplTest.java
  services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/KubernetesBasedAdapterInstanceStatusServiceTest.java
  services/command-router-quarkus/pom.xml
  services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
  services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/DeviceConnectionInfoProducer.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
  site/documentation/content/admin-guide/command-router-config.md
  site/homepage/content/release-notes.md
Labels: C&C

#2840 [#2830] Improve ensureTopicIsAmongSubscribedTopicPatternTopics()
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
Labels: C&C

#2841 [#2803] Fetch offset positions directly on partition assignment
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
Labels: bug, C&C
