Repository eclipse-hono/hono, pull requests merged in 2022-08, with the labels that each got.

#3364 [#3361] Change HTTP adapter idleTimeout default to 75s
  adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/HttpProtocolAdapterOptions.java
  adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/HttpProtocolAdapterProperties.java
  adapters/http-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
  service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceConfigOptions.java
  service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceConfigProperties.java
  service-base/src/test/java/org/eclipse/hono/service/http/HttpServiceConfigOptionsTest.java
  service-base/src/test/resources/http-service-config-options.yaml
  site/documentation/content/admin-guide/http-adapter-config.md
  site/documentation/content/user-guide/http-adapter.md
Labels: bug, HTTP Adapter

#3374 [#3372] Allow building of docker images for windows
  adapters/parent/pom.xml
  services/parent/pom.xml
Labels: enhancement, build system

#3373 [#3366] Fix of non-closing future in HTTP adapter
  adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/http-base/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
Labels: enhancement, HTTP Adapter

#3382 [#3333] Use build-in collector in Jaeger All-In-One, instead of separate collector component
  bom/pom.xml
  tests/pom.xml
  tests/src/test/resources/otel-collector/otel-collector-config.yaml
Labels: enhancement, Tracing

#3383 Adapt HTTP error logging
  service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
Labels: enhancement

#3385 Rename notification 'enabled' field/getter
  adapters/amqp/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotification.java
  clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotification.java
  clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotificationTest.java
  clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotificationTest.java
  clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClient.java
  clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
  services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementServiceTest.java
  services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementServiceTest.java
Labels: enhancement

#3384 [#3379] Improve KubernetesBasedAdapterInstanceStatusService
  core/src/main/java/org/eclipse/hono/util/CommandConstants.java
  core/src/test/java/org/eclipse/hono/util/CommandConstantsTest.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/KubernetesBasedAdapterInstanceStatusService.java
  services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/KubernetesBasedAdapterInstanceStatusServiceTest.java
Labels: bug, C&C

#3371 [#3369] Deploy all client modules to Maven Central
  jenkins/Hono-Deploy-Maven-Central-Pipeline-Declarative.groovy
Labels: bug, build system

#3380 [#3378] Fix NPE in case CoAP PUT URI device id is empty
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
  adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/AbstractHonoResourceTest.java
Labels: bug, CoAP Adapter

#3387 [#2355] Close tenant-scoped links when not needed anymore
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
Labels: enhancement, C&C

#3388 [#3360] Create native executable command line client
  builder/HonoBuilder.dockerfile
  cli/pom.xml
  jenkins/Hono-Deploy-Eclipse-Pipeline-Declarative.groovy
  jenkins/Hono-Deploy-Maven-Central-Pipeline-Declarative.groovy
  jenkins/Hono-Nightly-Pipeline-Declarative.groovy
  jenkins/Hono-Release-Pipeline.groovy
  jenkins/Hono-Sonar-Pipeline.groovy
  jenkins/Hono-Website-Pipeline-Declarative.groovy
  site/documentation/content/getting-started/_index.md
Labels: enhancement, build system

#3391 [#3390] Allow CLI to send empty messages with no content type
  cli/src/main/java/org/eclipse/hono/cli/CustomConfiguration.java
  cli/src/main/java/org/eclipse/hono/cli/adapter/amqp/AmqpAdapter.java
  cli/src/main/java/org/eclipse/hono/cli/app/CommandAndControl.java
  cli/src/main/java/org/eclipse/hono/cli/util/CommandUtils.java
  clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/EventSender.java
  clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/TelemetrySender.java
  clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/ProtonBasedAmqpAdapterClient.java
  clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/AmqpAdapterClientTestBase.java
  clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/impl/CommandResponderTest.java
  clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/impl/TelemetrySenderTest.java
Labels: bug, Client

#3394 [#3222] Handle empty messages uniformly across adapters
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
  adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
  adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/AbstractHonoResourceTest.java
  adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/TelemetryResourceTest.java
  clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/DownstreamAmqpMessageFactory.java
  clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/AmqpUtils.java
  clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandResponseSender.java
  clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
  core/src/main/java/org/eclipse/hono/util/EventConstants.java
  site/documentation/content/user-guide/amqp-adapter.md
  site/documentation/content/user-guide/coap-adapter.md
  site/documentation/content/user-guide/http-adapter.md
  site/documentation/content/user-guide/mqtt-adapter.md
  site/homepage/content/release-notes.md
  tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
Labels: MQTT Adapter, HTTP Adapter, AMQP Adapter, CoAP Adapter

#3396 Fix potential NPEs
  cli/src/main/java/org/eclipse/hono/cli/app/NorthBoundApis.java
  clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/tracing/MessageAnnotationsInjectAdapter.java
  clients/client-common/src/main/java/org/eclipse/hono/client/util/DownstreamMessageProperties.java
  core/src/main/java/org/eclipse/hono/config/AbstractConfig.java
  core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
  services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/Statement.java
  services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/ClasspathSchemaCreator.java
Labels: enhancement
