Repository eclipse-hono/hono, pull requests merged in 2022-07, with the labels that each got.

#3326 [#3325] Let binding of Kafka metrics be done via MicrometerRecorder
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/KafkaClientMetricsSupport.java
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/KafkaClientMetricsSupportProducer.java
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/MicrometerKafkaClientMetricsSupport.java
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/NoopKafkaClientMetricsSupport.java
  clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/metrics/MicrometerKafkaClientMetricsSupportTest.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/app/Application.java
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/KafkaMetricsSupportProducer.java
Labels: bug, Metrics

#3317 [#3131] Extend invalidating cache in protocol adapters.
  adapters/amqp/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
  adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
  clients/notification-amqp/src/test/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiverTest.java
  clients/notification-amqp/src/test/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationSenderTest.java
  clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationReceiverTest.java
  clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationSenderTest.java
  clients/notification/src/main/java/org/eclipse/hono/notification/NotificationConstants.java
  clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotification.java
  clients/notification/src/test/java/org/eclipse/hono/notification/NotificationEventBusSupportTest.java
  clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotificationTest.java
  clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
  clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
  clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClientTest.java
  core/src/main/java/org/eclipse/hono/util/TenantConstants.java
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementService.java
  site/documentation/content/api/tenant/index.md
  tests/src/test/java/org/eclipse/hono/tests/client/KafkaBasedEventSenderIT.java
Labels: enhancement, MQTT Adapter, HTTP Adapter, AMQP Adapter, CoAP Adapter, LoRa Adapter, SigFox Adapter

#3330 [#3327] Upgrade to Quarkus 2.10.2
  bom/pom.xml
  client-device-connection-infinispan/pom.xml
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/AdapterInstanceStatusProvider.java
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/UnknownStatusProvider.java
  legal/src/main/resources/legal/DEPENDENCIES
  legal/src/main/resources/legal/hono-maven.deps
  service-base/src/main/resources/META-INF/native-image/org.eclipse.hono/hono-service-base/native-image.properties
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/AdapterInstanceStatusService.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/app/Application.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/app/DeviceConnectionInfoProducer.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/UnknownStatusProvidingService.java
  services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImplTest.java
Labels: enhancement

#3335 [#3318] Add rate-limiting OpenTelemetry tracing sampler
  service-base/src/main/java/org/eclipse/hono/service/tracing/DropBySpanNamePrefixSampler.java
  service-base/src/main/java/org/eclipse/hono/service/tracing/RateLimitingSampler.java
  service-base/src/main/java/org/eclipse/hono/service/tracing/SamplerProducer.java
  site/documentation/content/admin-guide/monitoring-tracing-config.md
Labels: enhancement, Tracing

#3324 [#3306] Change default messaging network to Kafka
  adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
  clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClientProvider.java
  clients/client-common/src/test/java/org/eclipse/hono/client/util/MessagingClientProviderTest.java
  site/documentation/content/admin-guide/amqp-network-config.md
  site/documentation/content/admin-guide/common-config.md
  site/documentation/content/admin-guide/file-based-device-registry-config.md
  site/documentation/content/admin-guide/hono-kafka-client-configuration.md
  site/documentation/content/admin-guide/jdbc-device-registry-config.md
  site/documentation/content/admin-guide/mongodb-device-registry-config.md
  site/homepage/content/release-notes.md
Labels: enhancement

#3334 Remove obsolete jakarta.ws.rs-api dependency
  adapters/parent/pom.xml
  bom/pom.xml
  legal/src/main/resources/legal/DEPENDENCIES
  legal/src/main/resources/legal/hono-maven.deps
  services/parent/pom.xml
Labels: enhancement

#3338 [#3306] Change default messaging network to Kafka
  adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
  clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClientProvider.java
  clients/client-common/src/test/java/org/eclipse/hono/client/util/MessagingClientProviderTest.java
  site/documentation/content/admin-guide/amqp-network-config.md
  site/documentation/content/admin-guide/common-config.md
  site/documentation/content/admin-guide/file-based-device-registry-config.md
  site/documentation/content/admin-guide/hono-kafka-client-configuration.md
  site/documentation/content/admin-guide/jdbc-device-registry-config.md
  site/documentation/content/admin-guide/mongodb-device-registry-config.md
  site/homepage/content/release-notes.md
Labels: enhancement

#3343 Log stacktrace of vert.x shutdown only if closed unexpectedly
  service-base/src/main/java/org/eclipse/hono/service/AbstractServiceApplication.java
Labels: enhancement

#3341 [#3339] Use configured Kafka consumer group id in Command Router
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
  tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
Labels: enhancement, C&C

#3344 [#3340] Add option to disable delivery failure command responses
  clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
Labels: enhancement, C&C

#3337 Add support for disabling protocol adapters selectively in ITs
  tests/pom.xml
  tests/readme.md
  tests/src/test/java/org/eclipse/hono/tests/EnabledIfProtocolAdaptersAreRunning.java
  tests/src/test/java/org/eclipse/hono/tests/EnabledIfProtocolAdaptersAreRunningCondition.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/EventAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryJmsQoS1IT.java
  tests/src/test/java/org/eclipse/hono/tests/coap/EventCoapIT.java
  tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/CorsIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
  tests/src/test/java/org/eclipse/hono/tests/lora/LoraIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
Labels: enhancement, build system

#3347 [#2892] Fix IllegalStateException in HTTP Adapter
  adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
Labels: bug, HTTP Adapter

#3348 [#3302] Add resource for downloading JWK set
  bom/pom.xml
  legal/src/main/resources/legal/DEPENDENCIES
  legal/src/main/resources/legal/hono-maven.deps
  service-base/pom.xml
  service-base/src/main/java/org/eclipse/hono/service/auth/AuthTokenFactory.java
  service-base/src/main/java/org/eclipse/hono/service/auth/JjwtBasedAuthTokenFactory.java
  service-base/src/main/java/org/eclipse/hono/service/auth/JjwtBasedAuthTokenValidator.java
  service-base/src/main/java/org/eclipse/hono/service/auth/JwtSupport.java
  service-base/src/main/java/org/eclipse/hono/service/auth/SignatureSupportingConfigProperties.java
  service-base/src/main/java/org/eclipse/hono/service/auth/SignatureSupportingOptions.java
  service-base/src/main/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientConfigProperties.java
  service-base/src/main/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientOptions.java
  service-base/src/main/java/org/eclipse/hono/service/auth/delegating/quarkus/DelegatingAuthenticationServiceProducer.java
  service-base/src/test/java/org/eclipse/hono/service/auth/AuthTokenFactoryTest.java
  service-base/src/test/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientOptionsTest.java
  service-base/src/test/resources/auth-server-client-options.yaml
  services/auth-base/pom.xml
  services/auth-base/src/main/java/org/eclipse/hono/authentication/JwkResource.java
  services/auth-base/src/test/java/org/eclipse/hono/authentication/file/FileBasedAuthenticationServiceOptionsTest.java
  services/auth-base/src/test/resources/auth-service-options.yaml
  services/auth/src/main/java/org/eclipse/hono/authentication/app/Application.java
  services/auth/src/main/java/org/eclipse/hono/authentication/app/PropertiesProducer.java
  site/documentation/content/admin-guide/auth-server-config.md
  site/documentation/content/admin-guide/command-router-config.md
  site/documentation/content/admin-guide/jdbc-device-registry-config.md
  site/documentation/content/admin-guide/mongodb-device-registry-config.md
  site/homepage/content/release-notes.md
  tests/pom.xml
  tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
  tests/src/test/java/org/eclipse/hono/tests/auth/AuthServerAmqpIT.java
  tests/src/test/resources/commandrouter/clustered-cache/application.yml
  tests/src/test/resources/commandrouter/embedded-cache/application.yml
Labels: Auth Server, Feature Request

#3342 [#2828] Add metrics support to JDBC based registry
  services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/tenant/AbstractTenantStore.java
  services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/tenant/ManagementStore.java
  services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/tenant/base.sql.yaml
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/metrics/DeviceRegistryMetrics.java
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/metrics/DeviceRegistryMetricsAdapter.java
  services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/app/JdbcBasedDeviceRegistryMetrics.java
  services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/MicrometerBasedMongoDbDeviceRegistryMetrics.java
  services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/app/ManagementServicesProducer.java
  services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/app/MetricsFactory.java
  services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/app/MongoDbBasedDeviceRegistryMetrics.java
  site/documentation/content/api/Metrics.md
Labels: Feature Request, JDBC Device Registry

#3351 [#3327] Apply tracing changes related to Quarkus 2.10.2 update
  adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  bom/pom.xml
  service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
  service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
  service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
Labels: enhancement, Tracing

#3352 Rename AssumeMessagingSystem annotation
  tests/src/test/java/org/eclipse/hono/tests/AssumeMessagingSystemCondition.java
  tests/src/test/java/org/eclipse/hono/tests/EnabledIfMessagingSystemConfigured.java
  tests/src/test/java/org/eclipse/hono/tests/EnabledIfMessagingSystemConfiguredCondition.java
  tests/src/test/java/org/eclipse/hono/tests/EnabledIfRegistrySupportsFeaturesCondition.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryJmsQoS1IT.java
  tests/src/test/java/org/eclipse/hono/tests/client/AmqpApplicationClientIT.java
  tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
  tests/src/test/java/org/eclipse/hono/tests/client/KafkaBasedEventSenderIT.java
  tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
  tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistryNotificationsIT.java
Labels: enhancement

#3350 [#3312] Remove timeout on initial subscribeAndWaitForRebalance()
  clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
  tests/pom.xml
Labels: enhancement

#3356 [#3301] Use request URI pattern as Span name
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/CommandResponseResource.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/EventResource.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/TelemetryResource.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
  adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/AbstractHonoResourceTest.java
  adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResourceTest.java
Labels: C&C, Feature Request

#3355 [#3302] Support setting of alg on validating keys
  deploy/src/main/sandbox/hono-values.yml
  service-base/src/main/java/org/eclipse/hono/service/auth/JjwtBasedAuthTokenFactory.java
  service-base/src/main/java/org/eclipse/hono/service/auth/JjwtBasedAuthTokenValidator.java
  service-base/src/main/java/org/eclipse/hono/service/auth/JwtSupport.java
  service-base/src/main/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientConfigProperties.java
  service-base/src/main/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientOptions.java
  service-base/src/test/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientOptionsTest.java
  service-base/src/test/resources/auth-server-client-options.yaml
  tests/src/test/java/org/eclipse/hono/tests/auth/AuthServerAmqpIT.java
Labels: enhancement, Auth Server

#3359 Remove PreDestroy annotation in MongoDbBasedDao
  services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDao.java
Labels: enhancement

#3362 [#2660] Prevent "already creating client for key" errors
  clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/AbstractRequestResponseServiceClient.java
  clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/SenderCachingServiceClient.java
  clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java
  clients/client-common/src/main/java/org/eclipse/hono/client/util/ClientFactory.java
  clients/client-common/src/test/java/org/eclipse/hono/client/util/CachingClientFactoryTest.java
  clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/ProtonBasedAmqpAdapterClient.java
  clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiver.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
Labels: enhancement, Client

#3357 Refactor HonoKafkaConsumer topic subscription update
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
  tests/src/test/java/org/eclipse/hono/tests/client/AsyncHandlingAutoCommitKafkaConsumerIT.java
  tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
Labels: enhancement
