Repository eclipse-hono/hono, pull requests merged in 2023-10, with the labels that each got.

#3554 Update commit requirements in Contributing page
  CONTRIBUTING.md
  site/homepage/content/community/contributing.md
Labels: website

#3553 [#3557] Implement LoRa Actility triangulated device location support
  adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/providers/ActilityBaseProvider.java
  adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/providers/ActilityEnterpriseProvider.java
  adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/providers/ActilityWirelessProvider.java
  adapters/lora/src/test/java/org/eclipse/hono/adapter/lora/providers/ActilityEnterpriseProviderTest.java
  adapters/lora/src/test/java/org/eclipse/hono/adapter/lora/providers/ActilityWirelessProviderTest.java
  adapters/lora/src/test/resources/payload/actilityEnterprise.uplink.json
  adapters/lora/src/test/resources/payload/actilityWireless.uplink.json
  legal/src/main/resources/legal/NOTICE.md
Labels: LoRa Adapter, Feature Request

#3561 Prevent duplicate workflow runs when pushing pull requests
  .github/workflows/ci.yml
Labels: enhancement, build system

#3546 [#3537] Get K8s container id via K8s API.
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
  clients/command/pom.xml
  clients/command/src/main/java/org/eclipse/hono/client/command/CommandRoutingUtil.java
  clients/command/src/main/java/org/eclipse/hono/client/command/KubernetesContainerInfoProvider.java
  clients/command/src/main/java/org/eclipse/hono/client/command/ProtocolAdapterCommandConsumerFactoryImpl.java
  clients/command/src/test/java/org/eclipse/hono/client/command/KubernetesContainerInfoProviderTest.java
  clients/command/src/test/java/org/eclipse/hono/client/command/ProtocolAdapterCommandConsumerFactoryTest.java
Labels: C&C

#3565 Replace deprecated quarkus properties
  adapter-base/src/test/resources/application.yml
  adapters/amqp/src/test/resources/application.yml
  adapters/coap/src/test/resources/application.yml
  adapters/http-base/src/test/resources/application.yml
  adapters/lora/src/test/resources/application.yml
  adapters/mqtt-base/src/test/resources/application.yml
  bom/pom.xml
  cli/src/main/resources/application.yaml
  examples/protocol-gateway-example/src/main/resources/application.yml
  service-base/src/test/resources/application.yml
  services/auth-base/src/test/resources/application.yml
  services/command-router/src/test/resources/application.yml
  services/device-registry-base/src/test/resources/application.yml
  services/device-registry-jdbc/src/test/resources/application.yml
  services/device-registry-mongodb/src/main/resources/application.properties
  services/device-registry-mongodb/src/test/resources/application.yml
  tests/src/test/resources/amqp/application.yml
  tests/src/test/resources/auth/application.yml
  tests/src/test/resources/coap/application.yml
  tests/src/test/resources/commandrouter/clustered-cache/application.yml
  tests/src/test/resources/commandrouter/embedded-cache/application.yml
  tests/src/test/resources/deviceregistry-jdbc-h2/application.yml
  tests/src/test/resources/deviceregistry-jdbc-postgres/application.yml
  tests/src/test/resources/deviceregistry-mongodb/application.yml
  tests/src/test/resources/http/application.yml
  tests/src/test/resources/lora/application.yml
  tests/src/test/resources/mqtt/application.yml
Labels: enhancement

#3571 [#3566] Replace direct Vert.x CompositeFuture method calls with Future method calls
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
  adapter-base/src/main/java/org/eclipse/hono/adapter/MessagingClientProviders.java
  adapters/amqp/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/CommandResponseResource.java
  adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
  adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/LoraCommandSubscriptions.java
  adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
  cli/src/main/java/org/eclipse/hono/cli/app/TelemetryAndEvent.java
  client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
  clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImpl.java
  clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
  clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClientProvider.java
  clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandRouterClient.java
  clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumer.java
  clients/command/src/main/java/org/eclipse/hono/client/command/ProtocolAdapterCommandConsumerFactoryImpl.java
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
  clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiver.java
  examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
  service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
  service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
  services/auth/src/main/java/org/eclipse/hono/authentication/app/Application.java
  services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/device/TableManagementStore.java
  services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/tenant/ManagementStore.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/app/Application.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/pubsub/PubSubBasedCommandConsumerFactoryImpl.java
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/pubsub/PubSubBasedMappingAndDelegatingCommandHandler.java
  services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedMappingAndDelegatingCommandHandlerTest.java
  services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
  services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueueTest.java
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/AbstractDeviceRegistryApplication.java
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationService.java
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/DelegatingCredentialsManagementHttpEndpoint.java
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpoint.java
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/DelegatingTenantManagementHttpEndpoint.java
  services/device-registry-base/src/test/java/org/eclipse/hono/service/management/tenant/AbstractTenantManagementSearchTenantsTest.java
  services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
  services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/JdbcBasedTenantManagementSearchTenantsTest.java
  services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/ResolveGroupsTest.java
  services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDBBasedDeviceManagementSearchDevicesTest.java
  services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
  services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
  tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
  tests/src/test/java/org/eclipse/hono/tests/auth/AuthServerAmqpIT.java
  tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
  tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
  tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
  tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
  tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistryNotificationsIT.java
  tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
Labels: enhancement

#3572 Replace deprecated Maven plugin config properties
  adapters/pom.xml
  services/device-registry-mongodb/pom.xml
  services/pom.xml
  tests/pom.xml
Labels: build system

#3560 Use Mongo 6.0 by default
  .github/workflows/ci.yml
  bom/pom.xml
  services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbTestUtils.java
  site/documentation/content/admin-guide/mongodb-device-registry-config.md
  site/homepage/content/release-notes.md
Labels: MongoDB Device Registry

#3575 [#3574] Fix wrong context used in PubSubPublisherClient.publish().
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherClientImpl.java
  site/homepage/content/release-notes.md
Labels: bug, C&C

#3559 Make HonoKafkaConsumer compatible with Kafka 3.5
  clients/kafka-common/pom.xml
  clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
  clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumerTest.java
  test-utils/core-test-utils/src/main/java/org/eclipse/hono/test/JUnitTests.java
  tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
  tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
  tests/src/test/resources/logback-test-include-prod.xml
Labels: enhancement, C&C

#3578 Fix NPE when running CLI
  cli/src/main/java/org/eclipse/hono/cli/adapter/amqp/AmqpAdapter.java
  cli/src/main/java/org/eclipse/hono/cli/app/CommandAndControl.java
  cli/src/main/java/org/eclipse/hono/cli/util/ConnectionOptions.java
Labels: Client

#3577 Use Kafka in Raft mode for running integration tests
  bom/pom.xml
  site/homepage/content/release-notes.md
  tests/pom.xml
  tests/readme.md
  tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
Labels: enhancement, build system

#3579 Add @mattkaem as committer in the parent pom.
  pom.xml
Labels: documentation
