Repository eclipse-hono/hono, pull requests merged in 2023-06, with the labels that each got.

#3496 Update to Quarkus 2.16.7.Final
  bom/pom.xml
  create_dependencies_list.sh
  legal/src/main/resources/legal/DEPENDENCIES
  legal/src/main/resources/legal/hono-maven.deps
Labels: enhancement

#3498 [#3497] Increase performance of Pub/Sub topic and subscription creation
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumer.java
  clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumerTest.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubBasedAdminClientManager.java
Labels: enhancement

#3503 Enable clients requesting server time in CoAP responses
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/CoapConstants.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
  adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/option/TimeOption.java
  adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/CoapContextTest.java
  bom/pom.xml
  legal/src/main/resources/legal/NOTICE.md
  site/documentation/content/user-guide/coap-adapter.md
  tests/pom.xml
  tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
Labels: CoAP Adapter, Feature Request

#3508 Fix the legal entity type of Controlant in the copyright holders
  legal/src/main/resources/legal/NOTICE.md
Labels: documentation
