Repository eclipse-hono/hono, pull requests merged in 2023-04, with the labels that each got.

#3473 #3471 Add Pub/Sub subscriber functionality
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSender.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubMessageHelper.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/CachingPubSubPublisherFactory.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherClient.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherClientImpl.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherFactory.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/CachingPubSubSubscriberFactory.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/PubSubSubscriberClient.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/PubSubSubscriberClientImpl.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/PubSubSubscriberFactory.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSenderTest.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/PubSubMessageHelperTest.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/publisher/CachingPubSubPublisherFactoryTest.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/subscriber/CachingPubSubSubscriberFactoryTest.java
  clients/telemetry-pubsub/src/main/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSender.java
  clients/telemetry-pubsub/src/test/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSenderTest.java
  site/documentation/content/admin-guide/pubsub-config.md
Labels: C&C

#3475 [#2825] Support of generated authId at X509CertificateCredential
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateCredential.java
  services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceAndGatewayAutoProvisioner.java
  services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsServiceTestBase.java
  services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
  site/documentation/content/concepts/device-provisioning/index.md
  tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
  tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
  tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
  tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java
Labels: Device Registry, Feature Request

#3481 [#3471] Add notification functionality with Pub/Sub
  adapter-base/pom.xml
  adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
  bom/pom.xml
  clients/notification-pubsub/pom.xml
  clients/notification-pubsub/src/main/java/org/eclipse/hono/client/notification/pubsub/PubSubBasedNotificationReceiver.java
  clients/notification-pubsub/src/main/java/org/eclipse/hono/client/notification/pubsub/PubSubBasedNotificationSender.java
  clients/notification-pubsub/src/test/java/org/eclipse/hono/client/notification/pubsub/PubSubBasedNotificationReceiverTest.java
  clients/notification-pubsub/src/test/java/org/eclipse/hono/client/notification/pubsub/PubSubBasedNotificationSenderTest.java
  clients/pom.xml
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSender.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubMessageHelper.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/CachingPubSubPublisherFactory.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherFactory.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSenderTest.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/PubSubMessageHelperTest.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/publisher/CachingPubSubPublisherFactoryTest.java
  clients/telemetry-pubsub/src/main/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSender.java
  clients/telemetry-pubsub/src/test/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSenderTest.java
  service-base/pom.xml
  service-base/src/main/java/org/eclipse/hono/service/NotificationSupportingServiceApplication.java
  services/command-router/pom.xml
  services/command-router/src/main/java/org/eclipse/hono/commandrouter/app/Application.java
  services/device-registry-base/pom.xml
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/AbstractAmqpServerFactory.java
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/CommonConfigPropertiesProducer.java
  services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/NotificationSenderProducer.java
  site/documentation/content/admin-guide/file-based-device-registry-config.md
  site/documentation/content/admin-guide/jdbc-device-registry-config.md
  site/documentation/content/admin-guide/mongodb-device-registry-config.md
Labels: C&C, Feature Request

#3483 [#3471] Add Pub/Sub based Command & Control API
  site/documentation/content/admin-guide/command-router-config.md
  site/documentation/content/admin-guide/common-config.md
  site/documentation/content/admin-guide/pubsub-config.md
  site/documentation/content/api/command-and-control-pubsub/index.md
  site/documentation/content/api/tenant/index.md
Labels: documentation, C&C

#3484 [#3471] Add Pub/Sub based Command & Control Implementation
  bom/pom.xml
  clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommand.java
  clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandContext.java
  clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedInternalCommandSender.java
  clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommand.java
  clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
  clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandSender.java
  clients/command-pubsub/pom.xml
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedCommand.java
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedCommandContext.java
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedCommandResponseSender.java
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumer.java
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandSender.java
  clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedCommandContextTest.java
  clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedCommandResponseSenderTest.java
  clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedCommandTest.java
  clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumerTest.java
  clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandSenderTest.java
  clients/command/src/main/java/org/eclipse/hono/client/command/AbstractCommandContext.java
  clients/command/src/main/java/org/eclipse/hono/client/command/Command.java
  clients/command/src/main/java/org/eclipse/hono/client/command/CommandContext.java
  clients/command/src/main/java/org/eclipse/hono/client/command/Commands.java
  clients/command/src/test/java/org/eclipse/hono/client/command/CommandsTest.java
  clients/pom.xml
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubBasedAdminClientManager.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubMessageHelper.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/tracing/PubSubMessageExtractAdapter.java
  clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/tracing/PubSubTracingHelper.java
  clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/PubSubMessageHelperTest.java
  clients/telemetry-pubsub/src/main/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSender.java
  core/src/main/java/org/eclipse/hono/util/CommandConstants.java
Labels: C&C, Feature Request
