Repository eclipse-hono/hono, pull requests merged in 2023-07, with the labels that each got.

#3509 Update dependencies
  bom/pom.xml
  legal/src/main/resources/legal/DEPENDENCIES
  legal/src/main/resources/legal/hono-maven.deps
Labels: enhancement

#3506 Bump Eclipse Californium version
  bom/pom.xml
  legal/src/main/resources/legal/DEPENDENCIES
  legal/src/main/resources/legal/hono-maven.deps
Labels: enhancement, CoAP Adapter

#3516 Implement backend data field filter for H2 & Postgresql (similar to MongoDB)
  services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/device/TableManagementStore.java
  services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/device/base.h2.sql.yaml
  services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/device/base.postgresql.sql.yaml
  services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/device/base.sql.yaml
  services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/DeviceManagementServiceImpl.java
  services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/JdbcBasedDeviceManagementSearchDevicesTest.java
  site/documentation/content/api/management/device-registry-v1.yaml
  site/documentation/content/user-guide/device-registry.md
Labels: enhancement, JDBC Device Registry

#3521 [#3471] Bug fix for commands via Pub/Sub
  clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandSender.java
Labels: bug, C&C
